update drm interfaces to fix sts issue
projectceladon/device-androidia-mixins pull request #1034
Opened 2020-12-24 08:14 UTC by ruanhongfu

there're 2 reasons to remove default 1.3:
1. default implementation is actually unavailable from v1.1+
   update hardly to 1.3 causes sts failure.
2. for target-api level 5, drm interface v1.3 is allowed only,
   so removed 1.0/default to avoid compiling error.

Tracked-on: oam-95524
Signed-off-by: Ruan, Hongfu <hongfu.ruan@intel.com>

2020-12-24 08:35 UTC, JeevakaPrabu approved these changes

2020-12-29 19:55 UTC, JeevakaPrabu requested changes
@ruanhongfu with api level 30 enabled, check the logcat logs with this patch. There seems to be drm service exit

2020-12-31 01:21 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2854

2020-12-31 02:34 UTC, kaushlen approved these changes

2020-12-31 02:36 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2855

2021-12-23 03:19 UTC, closed without merging