audio server restart on boot complete
projectceladon/device-androidia-mixins pull request #1051
Opened 2021-01-14 07:39 UTC by gkdeepa

Since hda driver is unable to get the HDMI
sound devices, it is waiting till the timeout
and then listing the ALC256 cards.
By then Android would have started the Audioserver
and finds that there are no sink devices availabe.
Till we get the HDMI solution working this can be
a WA fix for the audio 3.5mm playback

Tracked-On: OAM-95721
Signed-off-by: gkdeepa g.k.deepa@intel.com

2021-01-15 04:02 UTC, sgnanase approved these changes

2021-01-15 04:18 UTC, JeevakaPrabu requested changes
As same branch used for CML, lets find a proper fix.

2021-01-18 07:11 UTC, balajim001 approved these changes
LGTM

2021-01-18 08:28 UTC, JeevakaPrabu approved these changes

2021-01-18 13:29 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2915

Done by "Deepa, G K" <g.k.deepa@intel.com>

2021-01-18 14:21 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1448

Done by "Deepa, G K" <g.k.deepa@intel.com>

2021-01-18 18:14 UTC, merged

2021-01-18 18:14 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Deepa, G K" <g.k.deepa@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2196