Use make, complier and linker from prebuilts
projectceladon/device-androidia-mixins pull request #1061
Opened 2021-01-25 07:21 UTC by yasoda-aravapalli

This is required to enable path restrictions
for Android 11

Tracked-On: OAM-95316
Signed-off-by: yaravapa <yasoda.aravapalli@intel.com>

2021-02-15 20:09 UTC, shyjumon-n approved these changes
Looks good to me. @JeevakaPrabu to give final approval.

2021-02-16 18:50 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3013

2021-02-17 05:56 UTC, JeevakaPrabu requested changes

2021-02-17 05:56 UTC, JeevakaPrabu commented on groups/kernel/AndroidBoard.mk
> +
one extra blank line can be removed

2021-02-17 05:56 UTC, JeevakaPrabu commented on groups/kernel/AndroidBoard.mk
> +      make -j24
why "-j24" ?

2021-02-17 06:26 UTC, JeevakaPrabu approved these changes

2021-02-19 11:35 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3018

Done by sys_cactusi <cactusi@intel.com>

2021-02-19 15:16 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1524

Done by sys_cactusi <cactusi@intel.com>

2021-02-20 00:17 UTC, merged

2021-02-20 00:17 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by sys_cactusi <cactusi@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2244