Auto hal for setting fixed performance
projectceladon/device-androidia-mixins pull request #1069
Opened 2021-02-08 12:59 UTC by shwethabolumbu

Based on the platform, set the fixed performance
scale factor to an integer as mentioned in Mode.aidl
of Power hal AIDL.

Tracked-On: OAM-95866
Signed-off-by: Shwetha B <shwetha.b@intel.com>

2021-02-08 13:36 UTC, kaushlen approved these changes

2021-02-08 13:50 UTC, JeevakaPrabu requested changes
Dont use ro.vendor.power.fixed_performance_scale_factor if you are going to set it on run time

2021-02-09 08:46 UTC, JeevakaPrabu approved these changes

2021-02-09 08:51 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2998

2021-02-09 13:00 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2999

Done by "B, Shwetha" <shwetha.b@intel.com>

2021-02-09 13:54 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1507

Done by "B, Shwetha" <shwetha.b@intel.com>

2021-02-09 20:47 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3000

Done by "B, Shwetha" <shwetha.b@intel.com>

2021-02-09 22:21 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1508

Done by "B, Shwetha" <shwetha.b@intel.com>

2021-02-10 08:47 UTC, merged

2021-02-10 08:48 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2234