drm: remove drm@1.0-service from mixins
projectceladon/device-androidia-mixins pull request #1129
Opened 2021-04-16 13:41 UTC by bkothapx

Tracked-On: OAM-96821
Signed-off-by: Kothapeta, BikshapathiX <bikshapathix.kothapeta@intel.com>

2021-04-19 09:06 UTC, sgnanase approved these changes

2021-04-19 09:06 UTC, sgnanase requested changes
Pls add tracked on field

2021-04-21 08:38 UTC, JeevakaPrabu requested changes
Please provided detailed issue and fix description in commit message

2021-04-22 16:56 UTC, JeevakaPrabu requested changes
please rewrite commit message as communicated

2021-04-23 03:22 UTC, ruanhongfu approved these changes

2021-04-23 04:06 UTC, JeevakaPrabu approved these changes

2021-04-23 04:28 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3186

2021-04-23 04:32 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3187

2021-04-23 09:31 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3185

Done by "Badrappan, Jeevaka" <jeevaka.badrappan@intel.com>

2021-04-23 10:12 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1658

Done by "Badrappan, Jeevaka" <jeevaka.badrappan@intel.com>

2021-04-23 13:58 UTC, merged

2021-04-23 13:59 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Badrappan, Jeevaka" <jeevaka.badrappan@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2341