Load sound kernel modules on demand rather than static
projectceladon/device-androidia-mixins pull request #1349
Opened 2022-03-10 16:28 UTC by padmashree9110

Tracked-On:
Signed-off-by: pmandri <padmashree.mandri@intel.com>

2022-03-17 05:53 UTC, JeevakaPrabu requested changes
- commit message should state the kernel config change to enable sof
- detail why loading bluetooth drivers on early-boot instead of post-fs
-

2022-03-17 07:34 UTC, JeevakaPrabu approved these changes

2022-03-17 16:19 UTC, JeevakaPrabu approved these changes

2022-03-18 05:16 UTC, balajim001 approved these changes
LGTM

2022-03-18 06:50 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4108

2022-03-18 10:40 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4109

Done by "Mandri, Padmashree" <padmashree.mandri@intel.com>

2022-03-18 12:35 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/2306

Done by "Mandri, Padmashree" <padmashree.mandri@intel.com>

2022-03-18 16:27 UTC, merged

2022-03-18 16:28 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Mandri, Padmashree" <padmashree.mandri@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2780