Resolve issue of usb card listing as sdcard
projectceladon/device-androidia-mixins pull request #1409
Opened 2022-06-28 11:48 UTC by padmashree9110

This changes resolves issue of usb getting detected
as sdcard in recovery mode.

Signed-off-by: pmandri <padmashree.mandri@intel.com>

2022-06-29 03:07 UTC, nitishat9 requested changes
It should be voldmanaged=udiska:auto to align it with the disk identifier

2022-06-29 05:18 UTC, sysopenci commented
Expected syntax:
    Commit message one-line summary

      Extra paragraphs can be added here.

      Longer description that explains the problem / solution
      or whatever that needs to be said

      It can contain
        multiple lines
        multiple paragraphs
        blank lines
        references

      But each paragraph must be followed by a blank line

      However, you need to keep the 'Tracked-On', 'Change-Id',
      'Signed-off-by', ..., fields in the **lastest** paragraph of
      the commit message.

      Change-Id: I9e58f79c7faf7f0edb9792e8b5322ab161331141
      Tracked-On: https://jira.server.ext/browse/PROJECTA-123
      Signed-off-by: Developer Name <developer.name@intel.com>

2022-06-29 05:37 UTC, nitishat9 approved these changes
LGTM

2022-06-29 05:40 UTC, balajim001 approved these changes
LGTM

2022-06-29 05:44 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4295

2022-06-29 11:32 UTC, shyjumon-n approved these changes
LGTM

2022-06-30 04:56 UTC, kaushlen approved these changes

2022-06-30 10:15 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4303

Done by "Mandri, Padmashree" <padmashree.mandri@intel.com>

2022-06-30 13:58 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/2448

Done by "Mandri, Padmashree" <padmashree.mandri@intel.com>

2022-06-30 19:49 UTC, merged

2022-06-30 19:50 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Mandri, Padmashree" <padmashree.mandri@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2868