Configure rro overlay for connectivity to fix CTS issue
projectceladon/device-androidia-mixins pull request #1475
Opened 2022-09-19 09:11 UTC by gollarx

configure the rro overlay for ServiceConnectivityResource to fix the Cts Net TC module issue.

Tracked-On: OAM-102959
Signed-off-by: gollarx <ratnakumarix.golla@intel.com>

2022-09-19 12:45 UTC, JeevakaPrabu requested changes
Please follow the commit message format:

<fix summary>
<blank line>
<Issue description>
<blank line>
<root cause>
<blank line>
<fix description>
<blank line>
Tracked-On: OAM-102959
Signed-off-by: gollarx <ratnakumarix.golla@intel.com>

2022-09-22 11:02 UTC, gollarx commented
Hello @JeevakaPrabu 

I have update the commit message, please review once.

2022-09-28 08:20 UTC, JeevakaPrabu approved these changes

2022-09-28 09:14 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/108

2022-09-28 09:42 UTC, JeevakaPrabu approved these changes

2022-09-28 14:09 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/109

Done by "Golla, RatnakumariX" <ratnakumarix.golla@intel.com>

2022-09-28 18:57 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_stable-premerge/builds/58

Done by "Golla, RatnakumariX" <ratnakumarix.golla@intel.com>

2022-09-28 23:17 UTC, merged

2022-09-28 23:18 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by cactusi@intel.com 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_stable-mergerequest/builds/39