Mixin-Update kernel config for 5.10 kernel
projectceladon/device-androidia-mixins pull request #1477
Opened 2022-09-20 05:10 UTC by bkothapx

lts2020-yocto: Enable android base and recommended configs.

Tracked-On: OAM-104003
Signed-off-by: Jeevaka Prabu Badrappan <jeevaka.badrappan@intel.com>
Signed-off-by: Kothapeta, Bikshapathi <bikshapathix.kothapeta@intel.com>

2022-09-21 04:26 UTC, kaushlen approved these changes

2022-09-30 09:05 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (caas), build-cels - r1 (caas_sriov), build-cels - r2 (r2_caas), build-cels - r2 (r2_caas_sriov) - extra

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/113

2022-10-14 06:00 UTC, rajucm2007 approved these changes
LGTM

2023-01-16 05:00 UTC, JeevakaPrabu requested changes
Similar change already integrated into celadon/s/mr0/stable. Please test with latest build and check the need for this PR

2023-01-17 08:01 UTC, JeevakaPrabu requested changes

2023-01-17 08:01 UTC, JeevakaPrabu commented on groups/kernel/gmin64/config-lts/lts2020-yocto/x86_64_defconfig
> +CONFIG_TRACEPOINTS=y
Check whether this change is needed

2023-01-17 08:01 UTC, JeevakaPrabu commented on groups/kernel/gmin64/config-lts/lts2020-yocto/x86_64_defconfig
> +CONFIG_TRACE_CLOCK=y
all the trace related configs needs to be double checked

2023-01-17 08:04 UTC, rajucm2007 approved these changes
LKGM

2023-01-17 08:16 UTC, bkothapx commented on groups/kernel/gmin64/config-lts/lts2020-yocto/x86_64_defconfig
> +CONFIG_TRACE_CLOCK=y
Yes this is already available in 
CELADON/device/intel/mixins/groups/kernel/gmin64/config-lts/lts2021-chromium/x86_64_defconfig

2023-01-17 08:16 UTC, bkothapx commented on groups/kernel/gmin64/config-lts/lts2020-yocto/x86_64_defconfig
> +CONFIG_TRACEPOINTS=y
Yes this is already available in 
CELADON/device/intel/mixins/groups/kernel/gmin64/config-lts/lts2021-chromium/x86_64_defconfig

2023-01-17 08:16 UTC, bkothapx commented on groups/kernel/gmin64/config-lts/lts2020-yocto/x86_64_defconfig
> +CONFIG_BINARY_PRINTF=y
Yes, this is already available in 
CELADON/device/intel/mixins/groups/kernel/gmin64/config-lts/lts2021-chromium/x86_64_defconfig

2023-01-17 08:16 UTC, bkothapx commented on groups/kernel/gmin64/config-lts/lts2020-yocto/x86_64_defconfig
> +CONFIG_KFENCE_NUM_OBJECTS=255
KFENCE is expected with these values else we observe its failing in VTS test case

2023-01-19 05:20 UTC, kaushlen approved these changes

2023-01-19 05:22 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/268

2023-01-19 05:27 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/269

2023-01-19 05:38 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/270

2023-01-24 04:58 UTC, JeevakaPrabu approved these changes

2023-01-24 08:15 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/272

Done by "Kothapeta, BikshapathiX" <bikshapathix.kothapeta@intel.com>

2023-01-24 08:45 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_stable-premerge/builds/169

Done by "Kothapeta, BikshapathiX" <bikshapathix.kothapeta@intel.com>

2023-01-24 10:55 UTC, merged

2023-01-24 10:55 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Kothapeta, BikshapathiX" <bikshapathix.kothapeta@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_stable-mergerequest/builds/129