Battery percentage for Android in Virtual Machine
projectceladon/device-androidia-mixins pull request #1569
Opened 2023-01-16 05:46 UTC by RajaniRanjan

mixin changes for health aidl support

Tracked-On: OAM-103170
Signed-off-by: Rajani Ranjan <rajani.ranjan@intel.com>

2023-01-16 05:47 UTC, sysopenci commented
Jira issue not in ['bug','improvement'], make sure jira issue is of type bug or improvement.

2023-01-17 08:23 UTC, sysopenci commented
Jira issue not in ['bug','improvement'], make sure jira issue is of type bug or improvement.

2023-01-23 05:35 UTC, JeevakaPrabu requested changes
Can you do the following changes in commit message
- "mixin changes to support health@aidl hal ." to "mixin changes to support health aidl hal" 
- fix typo "heath" => "health"

2023-01-23 06:08 UTC, sysopenci commented
Jira issue not in ['bug','improvement'], make sure jira issue is of type bug or improvement.

2023-01-23 09:44 UTC, sysopenci commented
Jira issue not in ['bug','improvement'], make sure jira issue is of type bug or improvement.

2023-02-06 05:57 UTC, JeevakaPrabu approved these changes

2023-02-06 06:47 UTC, vilasrk approved these changes

2023-02-06 09:21 UTC, balajim001 approved these changes
LGTM

2023-02-08 06:15 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4829

2023-02-08 06:56 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4834

2023-02-08 07:02 UTC, JeevakaPrabu approved these changes

2023-02-08 07:05 UTC, balajim001 approved these changes
LGTM

2023-02-08 07:13 UTC, JeevakaPrabu approved these changes

2023-02-08 14:36 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4835

Done by "Ranjan, Rajani" <rajani.ranjan@intel.com>

2023-02-08 17:57 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/2807

Done by "Ranjan, Rajani" <rajani.ranjan@intel.com>

2023-02-08 19:39 UTC, merged

2023-02-08 19:39 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Ranjan, Rajani" <rajani.ranjan@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/3202