linux-intel-lts2021: enable HWP and intel_pstate active mode
projectceladon/device-androidia-mixins pull request #1651
Opened 2023-05-31 01:53 UTC by qizhangz

Tracked-On: OAM-110531

2023-07-14 01:52 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-14 04:11 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-14 08:25 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-14 10:51 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-07-19 04:46 UTC, JeevakaPrabu requested changes
- Remove the prefix linux-intel-lts2021 as the change will apply to all kernels
- By disabling schedutil, intel_pstate is not set to passive. Change is not really setting intel_pstate to active but rather avoiding setting of intel_pstate to passive. If the real intention is to set it to active, then please set intel_pstate to active when schedutil is false

2023-07-28 06:33 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-28 07:01 UTC, qizhangz commented
> * Remove the prefix linux-intel-lts2021 as the change will apply to all kernels
> * By disabling schedutil, intel_pstate is not set to passive. Change is not really setting intel_pstate to active but rather avoiding setting of intel_pstate to passive. If the real intention is to set it to active, then please set intel_pstate to active when schedutil is false

made change as the comments.
Another PR to set schedutil to false https://github.com/projectceladon/device-androidia/pull/1710

2023-07-28 07:02 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-28 07:11 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-28 07:13 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-07-28 07:56 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-28 07:57 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-28 08:49 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-28 09:22 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-07-28 10:35 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-28 10:42 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-31 01:06 UTC, qizhangz commented
@JeevakaPrabu Could you help review the change?

2023-07-31 06:15 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-31 09:34 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-08-01 05:40 UTC, kaushlen approved these changes

2023-08-01 13:39 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/262

Done by "Zhang, Qi1" <qi1.zhang@intel.com>

2023-08-01 19:52 UTC, merged

2023-08-01 19:52 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Zhang, Qi1" <qi1.zhang@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/229

2023-08-01 19:53 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-01 22:03 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB