not load legacy camera binary for ivi build
projectceladon/device-androidia-mixins pull request #1659
Opened 2023-06-02 07:56 UTC by shivasku82

2023-06-02 07:57 UTC, sysopenci commented
Expected syntax:
    Commit message one-line summary

      Extra paragraphs can be added here.

      Longer description that explains the problem / solution
      or whatever that needs to be said

      It can contain
        multiple lines
        multiple paragraphs
        blank lines
        references

      But each paragraph must be followed by a blank line

      However, you need to keep the 'Tracked-On', 'Change-Id',
      'Signed-off-by', ..., fields in the **lastest** paragraph of
      the commit message.

      Change-Id: I9e58f79c7faf7f0edb9792e8b5322ab161331141
      Tracked-On: https://jira.server.ext/browse/PROJECTA-123
      Signed-off-by: Developer Name <developer.name@intel.com>

2023-06-06 07:05 UTC, neofang7 commented
Looks good to me

2023-06-06 08:19 UTC, balajim001 approved these changes
LGTM

2023-06-06 08:41 UTC, neofang7 approved these changes

2023-06-06 13:58 UTC, JeevakaPrabu requested changes
If the service is intended for mediation or other purpose, isn't it better to move it to new mixins instead of having the product check here? mixins is intended for this

2023-06-06 14:32 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/169

Done by "Rudrappa, Shiva Kumara" <shiva.kumara.rudrappa@intel.com>

2023-06-14 04:59 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/197

2023-06-14 05:09 UTC, balajim001 commented
vendor.camera.external=VHAL is this property rw ?

2023-06-14 05:10 UTC, balajim001 approved these changes
LGTM

2023-06-14 05:52 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-06-14 06:47 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-06-14 09:59 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (caas), build-cels - r1 (caas_sriov), build-cels - r1 (celadon_ivi), build-cels - r2 (r2_caas), build-cels - r2 (r2_caas_dev) - extra, build-cels - r2 (r2_caas_sriov), build-cels - r2 (r2_celadon_ivi)

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/198

2023-06-14 14:30 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (caas), build-cels - r1 (caas_sriov), build-cels - r1 (celadon_ivi), build-cels - r2 (r2_caas), build-cels - r2 (r2_caas_dev) - extra, build-cels - r2 (r2_caas_sriov), build-cels - r2 (r2_celadon_ivi)

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/200

2023-06-14 16:19 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-06-14 18:40 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/201

Done by "Rudrappa, Shiva Kumara" <shiva.kumara.rudrappa@intel.com>

2023-06-15 16:06 UTC, JeevakaPrabu commented on groups/camera-ext/ivi/product.mk
> +#PRODUCT_PACKAGES_DEBUG += TestingCamera
This can be under TARGET_BUILD_VARIANT check and included for eng, userdebug or removed completely

2023-06-15 16:08 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-06-15 20:52 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/204

Done by "Rudrappa, Shiva Kumara" <shiva.kumara.rudrappa@intel.com>

2023-06-16 03:59 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/118

Done by "Rudrappa, Shiva Kumara" <shiva.kumara.rudrappa@intel.com>

2023-06-16 07:04 UTC, merged

2023-06-16 07:04 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Rudrappa, Shiva Kumara" <shiva.kumara.rudrappa@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/125