Support userspace fastboot over USB
projectceladon/device-androidia-mixins pull request #1719
Opened 2023-08-17 13:06 UTC by GangSecurity

Fasbootd over USB support is required for IVI project Add TARGET_RECOVERY_UI_LIB := librecovery_ui_default to support this feature

Tracked-On: OAM-111782

2023-08-17 13:07 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-17 13:08 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-17 16:18 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-08-17 16:26 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-08-28 05:38 UTC, dyang23 approved these changes
LGTM

2023-08-28 05:47 UTC, yang8621 approved these changes

2023-08-28 06:09 UTC, JeevakaPrabu requested changes
typo in commit message "Fasbootd" => "Fastbootd"

2023-08-28 06:09 UTC, JeevakaPrabu commented on groups/device-specific/celadon_ivi/BoardConfig.mk
> +#fastbootd over USB support
to be inline with rest of the file, introduced a space between # and fastbootd. 
"# fastbootd over USB support"

2023-08-28 06:34 UTC, JeevakaPrabu approved these changes

2023-08-28 06:35 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-28 09:02 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-08-28 12:09 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/500

Done by "Chen, Gang G" <gang.g.chen@intel.com>

2023-08-28 12:10 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/324

Done by "Chen, Gang G" <gang.g.chen@intel.com>

2023-08-28 14:33 UTC, merged

2023-08-28 14:34 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Chen, Gang G" <gang.g.chen@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/305