Use sw vulkan driver in VIRTIO-3D mode
projectceladon/device-androidia-mixins pull request #1726
Opened 2023-08-24 01:56 UTC by chenyanxzhu

Found one caas virtio-gpu issue, which use intel Vulkan driver. Instead we need use pastel software vulkan driver

Tracked-On: OAM-111883

2023-08-24 01:57 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-24 02:04 UTC, feijiang1 approved these changes
LGTM

2023-08-24 04:21 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-09-15 11:20 UTC, feijiang1 approved these changes
LGTM

2023-09-15 11:21 UTC, feijiang1 commented
@JeevakaPrabu  Please help review

2023-09-15 13:30 UTC, JeevakaPrabu requested changes
Can we detailed commit message written like 

As virtio-gpu does not support hardware vulkan driver, updating the
property to pastel so software vulkan driver is used.

2023-09-18 01:24 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-09-18 02:29 UTC, JeevakaPrabu approved these changes

2023-09-18 02:31 UTC, feijiang1 approved these changes

2023-09-18 02:38 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/591

2023-09-18 02:41 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/592

2023-09-18 03:26 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-09-18 05:27 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/593

Done by "Jiang, Fei" <fei.jiang@intel.com>

2023-09-18 05:28 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/360

Done by "Jiang, Fei" <fei.jiang@intel.com>

2023-09-18 08:40 UTC, merged

2023-09-18 08:42 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by cactusi@intel.com 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/350

2023-09-18 08:42 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-09-18 08:58 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details