Enable optee in mixins
projectceladon/device-androidia-mixins pull request #1727
Opened 2023-08-24 07:27 UTC by jingdlu

2023-08-24 07:28 UTC, sysopenci commented
Improper Commit Message
Tracked on not found in commit message,
    make sure Tracked-On: Jira-ticket  is present.

2023-08-24 07:29 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-24 07:48 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-08-24 09:10 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-24 09:30 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-08-25 10:23 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-25 10:41 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-08-28 08:05 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-28 09:29 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-28 09:45 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-08-29 07:54 UTC, syan10 commented on groups/device-specific/celadon_ivi/framework_manifest.xml
>      <hal format="aidl">
suggest to split this into 2 commits, one is for enable optee basic and xtest, the other is for keymaster related changes

2023-08-31 10:27 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-31 10:33 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-31 10:40 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-08-31 10:53 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-08-31 15:01 UTC, JeevakaPrabu requested changes
Call out all the changes done in detailed commit message

2023-08-31 15:01 UTC, JeevakaPrabu commented on groups/optee/true/init.rc
> +    service tee-supplicantd /vendor/bin/tee-supplicant
no need to indent this line

2023-09-01 00:03 UTC, syan10 commented on groups/optee/false/product.mk
> +    android.hardware.gatekeeper@1.0-service.software \
remove this

2023-09-01 00:05 UTC, syan10 commented on groups/optee/true/BoardConfig.mk
> +OPTEE_PLATFORM ?= kbl
it should not only target to kbl, right?

2023-09-01 01:53 UTC, jingdlu commented on groups/optee/true/BoardConfig.mk
> +OPTEE_PLATFORM ?= kbl
https://github.com/op-tee-ia/optee_os only supports kbl platform. This is just for TA compiling, not for real TEE running.

2023-09-01 02:15 UTC, jingdlu commented on groups/optee/false/product.mk
> +    android.hardware.gatekeeper@1.0-service.software \
Will remove this file for now.

2023-09-01 02:18 UTC, jingdlu commented on groups/optee/true/init.rc
> +    service tee-supplicantd /vendor/bin/tee-supplicant
Thanks for your comments. BTW, I will remove kernel driver config change for this time, will commit it with optee driver patch together.

2023-09-01 02:23 UTC, jingdlu commented on groups/device-specific/celadon_ivi/framework_manifest.xml
>      <hal format="aidl">
Will remove keymaster change for this time.

2023-09-01 02:37 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-09-01 03:48 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-09-06 04:31 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (celadon_ivi), build-cels - r2 (r2_celadon_ivi) - extra

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/520

2023-09-06 06:04 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (celadon_ivi), build-cels - r2 (r2_celadon_ivi) - extra

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/522

2023-09-07 04:26 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (celadon_ivi), build-cels - r2 (r2_celadon_ivi) - extra

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/528

2023-09-07 07:27 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-09-07 07:39 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-09-07 08:31 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-09-07 10:37 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-09-07 10:40 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-09-07 12:46 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-09-08 02:16 UTC, JeevakaPrabu approved these changes

2023-09-08 04:28 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/539

Done by "Lu, Jingdong" <jingdong.lu@intel.com>

2023-09-08 04:29 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/348

Done by "Lu, Jingdong" <jingdong.lu@intel.com>

2023-09-08 09:09 UTC, merged

2023-09-08 09:10 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by cactusi@intel.com 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/334