unify mixin of optee and trusty into tee
projectceladon/device-androidia-mixins pull request #1761
Opened 2023-10-08 01:19 UTC by syan10

tee has 3 configurations:
-false:  none tee will be provided
-trusty: trusty os for tee
-optee:  optee os for tee

by default it will be set as false.

Tracked-On: OAM-112562

2023-10-08 03:28 UTC, JeevakaPrabu requested changes
in commit message. Can we change "none tee will be provided" to "none but tee will be provided" or "none. tee will be provided"

2023-10-09 00:32 UTC, kwang13 approved these changes

2023-10-09 03:21 UTC, JeevakaPrabu approved these changes

2023-10-09 05:06 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/705

2023-10-09 07:06 UTC, jingdlu commented on groups/tee/optee/product.mk
Do you need to add keymaster services into this file?

2023-10-09 07:39 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/706

Done by "Yan, Shaopu" <shaopu.yan@intel.com>

2023-10-09 07:58 UTC, syan10 commented on groups/tee/optee/product.mk
will do it later

2023-10-11 02:49 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/719

Done by "Yan, Shaopu" <shaopu.yan@intel.com>

2023-10-11 02:51 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/422

Done by "Yan, Shaopu" <shaopu.yan@intel.com>

2023-10-11 10:06 UTC, merged

2023-10-11 10:08 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/419