Add rules to build vbox guest additions modules
projectceladon/device-androidia-mixins pull request #1772
Opened 2023-10-12 01:27 UTC by YadongQi

Add build rules in AndroidBoard.mk to build vbox
guest additions modules.
Controll it by option: vbox_mods_version

Tracked-On: OAM-112344

2023-10-13 07:22 UTC, YadongQi commented
@JeevakaPrabu Please help review.

2023-10-17 01:41 UTC, JeevakaPrabu requested changes
Add rules to build vbox guest additions modules

Updated AndroidBoard.mk to build vbox guest module outside kernel tree.

vbox_mods_version option provided to control build of vbox guest module.

Tracked-On: OAM-112344
Signed-off-by: Yadong Qi <yadong.qi@intel.com>

set default value of vbox_mods_version to false in options.spec

2023-10-17 01:49 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-10-17 01:50 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-10-17 01:53 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-10-17 01:54 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-10-17 01:57 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-10-17 03:14 UTC, JeevakaPrabu approved these changes

2023-10-17 06:44 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-10-17 08:05 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-10-17 11:55 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_tmr0_master-preintegration/builds/24

Done by "Qi, Yadong" <yadong.qi@intel.com>

2023-10-17 11:56 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_tmr0_master-premerge/builds/8

Done by "Qi, Yadong" <yadong.qi@intel.com>

2023-10-18 05:27 UTC, merged

2023-10-18 05:28 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_tmr0_master-mergerequest/builds/16