Add-CONFIG_DRM_I915_MEMTRACK-kernel-config
projectceladon/device-androidia-mixins pull request #1839
Opened 2023-11-21 02:20 UTC by ShenghuaLinINTEL

this is to enable memtrack sysfs interface added to i915

2023-11-22 12:06 UTC, JeevakaPrabu requested changes
Add CONFIG_DRM_I915_MEMTRACK kernel config

Enable i915 memtrack driver that exposes sysfs interface to get GFX
shared memory usage.

Tests done:
- Call out the tests done

Tracked-On: OAM-112297
Signed-off-by: Lin, Shenghua <shenghua.lin@intel.com>

2023-11-23 02:23 UTC, ShenghuaLinINTEL commented
@JeevakaPrabu  fix done

2023-11-23 06:37 UTC, JeevakaPrabu approved these changes

2023-11-23 06:58 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1057

2023-11-23 10:35 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1058

Done by "Lin, Shenghua" <shenghua.lin@intel.com>

2023-11-27 01:43 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1073

2023-11-28 03:54 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1090

Done by "Lin, Shenghua" <shenghua.lin@intel.com>

2023-11-28 03:54 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/588

Done by "Lin, Shenghua" <shenghua.lin@intel.com>

2023-11-28 08:19 UTC, merged