Enable mediasdk h265 sw codec for cvmb
projectceladon/device-androidia-mixins pull request #1897
Opened 2024-04-11 09:01 UTC by harvan

2024-04-11 09:03 UTC, sysopenci commented
Improper Commit Message
Tracked on not found in commit message,
    make sure Tracked-On: Jira-ticket  is present.

2024-04-11 09:04 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check Android CI Web  for more details.

2024-04-11 09:49 UTC, sysopenci commented
Improper Commit Message
Tracked on not found in commit message,
    make sure Tracked-On: Jira-ticket  is present.

2024-04-11 09:50 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check Android CI Web  for more details.

2024-04-11 10:36 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-11 13:03 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue, Please check Android CI Web  for more details.

2024-04-11 13:15 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue, Please check Android CI Web  for more details.

2024-04-12 08:20 UTC, TianmiChen approved these changes

2024-04-15 07:59 UTC, shyjumon-n requested changes
Use the std commit msg format shared through IM

2024-04-15 08:02 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-15 10:10 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-15 10:25 UTC, harvan commented
> Use the std commit msg format shared through IM

It's done. 
Please review it again. Thanks.

2024-04-15 10:26 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-15 10:36 UTC, shyjumon-n approved these changes
LGTM

2024-04-15 12:25 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-15 14:31 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-15 16:01 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-15 16:31 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-16 20:49 UTC, merged

2024-04-16 21:08 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon_tmr0_master-merge/80