Enable CLANG kernel configs
projectceladon/device-androidia-mixins pull request #1900
Opened 2024-04-22 07:59 UTC by gowthambabu92

As CONFIG_CFI_CLANG is platform hardening requirement, updated configs to enable CLANG.

Tracked-On: OAM-116037

2024-04-22 08:01 UTC, sysopenci commented
Improper Commit Message
Jira issue not in ['bug','improvement'],
    make sure jira issue is of type bug or improvement.

2024-04-22 09:08 UTC, bpanda24 approved these changes
lgtm

2024-04-24 05:24 UTC, JeevakaPrabu requested changes
Please update the tests done with this change in commit message

2024-04-24 15:00 UTC, sysopenci commented
Improper Commit Message
Jira issue not in ['bug','improvement'],
    make sure jira issue is of type bug or improvement.

2024-04-25 08:59 UTC, JeevakaPrabu approved these changes

2024-05-06 15:44 UTC, JeevakaPrabu approved these changes

2024-05-07 09:14 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-05-07 16:37 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-05-07 20:45 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-05-08 01:01 UTC, merged

2024-05-08 01:20 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon-merge/457