Enable Virtio SPI Controller driver for Android VM.
projectceladon/device-androidia-mixins pull request #1968
Opened 2024-07-15 08:29 UTC by zhangqiang4

Tracked-On: OAM-122209

2024-07-16 06:09 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-16 09:15 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-17 06:37 UTC, xyzhao2018 approved these changes

2024-07-17 06:41 UTC, kaushlen approved these changes

2024-07-17 07:03 UTC, JeevakaPrabu requested changes
For each commit, please add Tests done: to commit message
As the driver is enabled in virt_diffconfig, is testing done with all lunch targets(caas, aaos)?

2024-07-17 07:39 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-17 10:04 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-17 12:04 UTC, JeevakaPrabu approved these changes

2024-07-17 18:31 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-17 23:17 UTC, merged

2024-07-17 23:34 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon-merge/670