Enable kprobes, uprobes and FUSE_BPF to fix STS error
projectceladon/device-androidia-mixins pull request #1977
Opened 2024-07-18 10:34 UTC by SaliniVenate

STS testcase testSetMaliciousStream was failing with warning: FuseDaemon: Rejected access to app-private dir on FUSE

Fix the issue by enabling kprobes, uprobes and fuse bpf drivers This patch is ported from base_aaos.

Tests Done: android.security.cts.WallpaperManagerTest#testSetMaliciousStream
Tracked-On: OAM-
Signed-off-by: Salini Venate <salini.venate@intel.com>

2024-07-18 10:35 UTC, sysopenci commented
Improper Commit Message
Proper Tracked on value is not present in
    commit message,make sure Tracked-on: jira-ticket is present

2024-07-19 05:19 UTC, shyjumon-n approved these changes
LGTM

2024-07-19 06:13 UTC, JeevakaPrabu requested changes
FUSE_BPF is already enabled so please remove it from commit message. you can mention something like "Enable fuse_bpf dependent driver modules"

2024-07-19 06:31 UTC, JeevakaPrabu approved these changes

2024-07-19 12:56 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-19 17:12 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-19 19:42 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-22 04:27 UTC, JeevakaPrabu approved these changes

2024-07-22 10:02 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-22 15:16 UTC, merged

2024-07-22 15:36 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon-merge/680