Add virtio over ivshmem for acrn andr QNX.
projectceladon/device-androidia-mixins pull request #2004
Opened 2024-08-12 06:25 UTC by YuanyuanZhao609

Tracked-On: OAM-119803

2024-08-12 06:26 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-12 06:27 UTC, sysopenci commented
Program name for this pr is not compatable with other dependent prs, for more details please check tracked_on

2024-08-12 06:28 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-13 13:25 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-14 06:20 UTC, xyzhao2018 commented on groups/kernel/gmin64/config-lts/linux-intel-lts2022/x86_64_defconfig
> +CONFIG_VIRTIO_IVSHMEM_GUEST_SHM=y
Please move virtualization related config to virt_diffconfig.

2024-08-14 07:47 UTC, bhe4 requested changes

2024-08-14 07:47 UTC, bhe4 commented on groups/kernel/gmin64/config-lts/linux-intel-lts2022/x86_64_defconfig
> +CONFIG_MEMORY_HOTPLUG=y
I checked some configurations are already exist in virt_diffconfig
CONFIG_IVSHM=y
CONFIG_IVSHM_IVSHMEM=y
CONFIG_IVSHM_GUEST_SHM=y

2024-08-14 07:47 UTC, bhe4 commented on groups/kernel/gmin64/config-lts/linux-intel-lts2022/x86_64_defconfig
> +CONFIG_RANDOMIZE_MEMORY_PHYSICAL_PADDING=0xa
what's the purpose to set it as 0xa?

2024-08-14 11:12 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-16 02:16 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-21 08:21 UTC, YuanyuanZhao609 commented on groups/kernel/gmin64/config-lts/linux-intel-lts2022/x86_64_defconfig
> +CONFIG_MEMORY_HOTPLUG=y
OK. Moved.

2024-08-21 08:22 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-22 06:21 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-22 18:40 UTC, JeevakaPrabu requested changes
in commit message there is a typo "andr" => "and"
Please add Tests done in commit message

2024-08-22 18:40 UTC, JeevakaPrabu commented on groups/kernel/gmin64/config-lts/linux-intel-lts2022/virt_diffconfig
> +CONFIG_VIRTIO_MEM=n
let's follow same format as rest of the file 
"# CONFIG_VIRTIO_IVSHMEM_DEBUG is not set"
"# CONFIG_VIRTIO_MEM is not set"

2024-08-22 18:40 UTC, JeevakaPrabu commented on groups/kernel/gmin64/config-lts/linux-intel-lts2022/x86_64_defconfig
> +CONFIG_TEST_HMM=n
let's follow same format as rest of the file 
"# CONFIG_TEST_HMM is not set"
"# CONFIG_FS_DAX is not set"

2024-08-23 05:26 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-23 07:11 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-26 01:31 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-27 05:36 UTC, ceiba1985 commented on groups/kernel/gmin64/config-lts/linux-intel-lts2022/virt_diffconfig
> +CONFIG_QNX_GUEST=y
Would better add a new line below the last line. Or .config cannot be generated successfully.

2024-08-28 15:35 UTC, YuanyuanZhao609 commented on groups/kernel/gmin64/config-lts/linux-intel-lts2022/virt_diffconfig
> +CONFIG_VIRTIO_MEM=n
OK.

2024-08-28 15:37 UTC, YuanyuanZhao609 commented on groups/kernel/gmin64/config-lts/linux-intel-lts2022/x86_64_defconfig
> +CONFIG_TEST_HMM=n
Changed format.

2024-08-28 15:39 UTC, YuanyuanZhao609 commented on groups/kernel/gmin64/config-lts/linux-intel-lts2022/virt_diffconfig
> +CONFIG_QNX_GUEST=y
Thank you. Add new line to config files.

2024-08-29 10:18 UTC, sysopenci commented
Program name for this pr is not compatable with other dependent prs, for more details please check tracked_on

2024-08-29 10:20 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-29 14:18 UTC, xyzhao2018 reviewed
Please remove the space line here.

2024-08-29 14:18 UTC, xyzhao2018 commented on groups/kernel/gmin64/config-lts/linux-intel-lts2022/qnx_diffconfig
> +
Please remove the space line here.

2024-08-29 14:19 UTC, xyzhao2018 reviewed
Please remove the space line here.

2024-08-29 14:19 UTC, xyzhao2018 commented on groups/kernel/gmin64/config-lts/linux-intel-lts2022/virt_diffconfig
> +
Please remove the space line here.

2024-08-29 16:07 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-29 16:24 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-30 01:01 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-30 03:46 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-30 08:40 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-30 09:10 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-30 09:36 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-30 10:23 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-09-02 07:33 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-09-02 12:10 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-09-02 13:30 UTC, xyzhao2018 approved these changes

2024-09-03 01:35 UTC, ceiba1985 approved these changes

2024-09-03 03:55 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-09-03 03:58 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-09-03 09:05 UTC, bing8deng approved these changes

2024-09-03 12:17 UTC, bhe4 approved these changes

2024-09-03 12:38 UTC, YuanyuanZhao609 commented
EB was tested, QNX and android works normally.

2024-09-03 12:38 UTC, JeevakaPrabu approved these changes

2024-09-03 12:53 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-09-03 17:24 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-09-03 22:16 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-09-04 00:58 UTC, zhy1030 approved these changes

2024-09-04 02:10 UTC, merged

2024-09-04 02:19 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details.