Adding needed permission for Processor
projectceladon/device-androidia-mixins pull request #2042
Opened 2024-09-12 10:23 UTC by mbajaj02

thermal-daemon doesn't have permission to access the cooling device therefore adding the needed permission.

Tracked-On: OAM-124670

2024-09-13 05:28 UTC, vilasrk approved these changes
LGTM

2024-09-13 05:31 UTC, vilasrk requested changes
Commit message length is more than 72 characters

2024-09-13 08:18 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-09-17 09:58 UTC, balajim001 approved these changes
LGTM

2024-09-18 06:56 UTC, vilasrk approved these changes
LGTM

2024-09-19 00:16 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-09-19 04:11 UTC, merged

2024-09-19 04:29 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon_umr0_master-merge/109