disable/enable sensors with respect to targets.
projectceladon/device-androidia-mixins pull request #2043
Opened 2024-09-13 10:59 UTC by RajaniRanjan

removing accelerometer and gyroscope sensors permission for base_aaos targets.Removing bsp_diff changes and merging it directly to repo projects.

Tracked-On: OAM-124722

2024-09-14 04:19 UTC, dyang23 approved these changes

2024-09-18 06:19 UTC, vilasrk requested changes
use target product instead of Product out

2024-09-18 09:52 UTC, vilasrk approved these changes
lgtm

2024-09-20 05:44 UTC, bing8deng requested changes

2024-09-20 05:44 UTC, bing8deng commented on groups/sensors/mediation/product.mk
>          frameworks/native/data/etc/android.hardware.sensor.light.xml:vendor/etc/permissions/android.hardware.sensor.light.xml
For base_aaos, can you disable light sensor also?

2024-09-23 08:19 UTC, bing8deng approved these changes

2024-09-23 12:01 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-09-25 03:44 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-09-25 05:53 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-09-25 16:16 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-09-25 19:48 UTC, merged

2024-09-25 20:08 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon_umr0_master-merge/131