Add mapper 2.1 support
projectceladon/device-androidia-mixins pull request #878
Opened 2020-09-16 03:39 UTC by renchenglei

This change is to help support mapper 2.1

Tracked-On: OAM-92929
Signed-off-by: Ren Chenglei <chenglei.ren@intel.com>

2020-09-18 07:34 UTC, feijiang1 approved these changes

2020-09-18 07:39 UTC, shyjumon-n approved these changes
Looks good to me, graphics team to final review

2020-09-18 11:07 UTC, JeevakaPrabu requested changes

2020-09-18 11:07 UTC, JeevakaPrabu commented on groups/device-specific/caas/product.mk
> +                    android.hardware.graphics.mapper@2.0-impl-2.1 \
Why do we need android.hardware.graphics.mapper@2.0-impl when we have added  android.hardware.graphics.mapper@2.0-impl-2.1 package?

2020-09-18 13:50 UTC, renchenglei commented on groups/device-specific/caas/product.mk
> +                    android.hardware.graphics.mapper@2.0-impl-2.1 \
I suppose this is a additional support for mapper. If there is some issues in mapper 2.1, we still could fall back to mapper 2.0.

> Why do we need [android.hardware.graphics.mapper@2.0-impl](mailto:android.hardware.graphics.mapper@2.0-impl) when we have added android.hardware.graphics.mapper@2.0-impl-2.1 package?

I suppose this is an additional support for mapper. If there are some issues in mapper 2.1, we still could fall back to mapper 2.0.

2020-09-18 15:13 UTC, JeevakaPrabu commented on groups/device-specific/caas/product.mk
> +                    android.hardware.graphics.mapper@2.0-impl-2.1 \
Could you please check the boot and other use cases with only android.hardware.graphics.mapper@2.0-impl-2.1 ?
I believe android.hardware.graphics.mapper@2.0-impl is not needed at all

2020-09-19 02:14 UTC, renchenglei commented on groups/device-specific/caas/product.mk
> +                    android.hardware.graphics.mapper@2.0-impl-2.1 \
@shyjumon-n, could you help confirm this? Especially the CTS on your side. Thanks a lot!

2024-12-01 17:43 UTC, closed without merging