mixins: storage: Add replacement for sdcardsfs
projectceladon/device-androidia-mixins pull request #885
Opened 2020-09-21 03:53 UTC by saranyagopal1

This patch adds fuse replacement for sdcardfs to
comply with Android 11 CDD.

Tracked-On: OAM-92905
Signed-off-by: Saranya Gopal <saranya.gopal@intel.com>

2020-09-21 10:43 UTC, shyjumon-n requested changes
I think it will be good to introduce a new mixin in storage, we can use the existing one till Q and R onwards we can have new one, what do you say ?

2020-09-21 10:50 UTC, saranyagopal1 commented
Yes, introducing a new mixin is also fine with me. 
Since Q MR0 is continuing in Q MR0 stable branch, I thought we can directly change this in master branch.

2020-09-23 08:42 UTC, kaushlen approved these changes

2020-09-23 08:51 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2472

2020-09-23 08:55 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2473

2020-09-23 11:28 UTC, shyjumon-n reviewed
Are you planning to enable this with a mixin.spec change right ? planning to do separately ?

2020-09-23 11:30 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2474

2020-09-23 11:30 UTC, saranyagopal1 commented
Yes, I will submit mixins.spec PR also.

2020-09-23 11:32 UTC, shyjumon-n approved these changes
Looks good to me

2020-09-24 09:54 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2479

Done by "Gopal, Saranya" <saranya.gopal@intel.com>

2020-09-24 16:49 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1238

Done by "Gopal, Saranya" <saranya.gopal@intel.com>

2020-09-24 19:42 UTC, merged