Enable Gatekeeper HAL
projectceladon/device-androidia-mixins pull request #933
Opened 2020-10-16 02:27 UTC by yang8621

There are two different binary dor the case:
Trusty enabled:
android.hardware.gatekeeper@1.0-service.trusty
Trusty disabled:
android.hardware.gatekeeper@1.0-service.software

The different sepolicy for the both are enabled.

Signed-off-by: Huang Yang <yang.huang@intel.com>

2020-10-16 06:09 UTC, ceiba1985 approved these changes

2020-10-17 13:30 UTC, sgnanase requested changes
Please add tracked on info

2020-10-18 02:15 UTC, yang8621 commented
> Please add tracked on info

Tracked-On: OAM-93148

2020-10-18 10:06 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2586

2020-10-19 05:09 UTC, JeevakaPrabu approved these changes

2020-10-19 05:12 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2590

2020-10-19 10:03 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2591

Done by "Huang, Yang" <yang.huang@intel.com>

2020-10-19 10:04 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1282

Done by "Huang, Yang" <yang.huang@intel.com>

2020-10-19 13:12 UTC, merged

2020-10-19 13:12 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Huang, Yang" <yang.huang@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2035