usb audio drivers are made as static
projectceladon/device-androidia-mixins pull request #981
Opened 2020-11-26 06:54 UTC by gkdeepa

Tracked-On:OAM-94556
Signed-off-by: Deepa G K <g.k.deepa@intel.com>
Signed-off-by: Balaji Manoharan m.balaji@intel.com

2020-11-26 08:40 UTC, balajim001 commented
please help provide patch description.

2020-11-26 08:40 UTC, balajim001 approved these changes
LGTM

2020-11-27 06:54 UTC, JeevakaPrabu requested changes
introduce a space between Tracked-On: and OAM-94556

2020-11-27 07:20 UTC, JeevakaPrabu approved these changes

2020-11-27 10:02 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2740

Done by "Deepa, G K" <g.k.deepa@intel.com>

2020-11-27 10:51 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1362

Done by "Deepa, G K" <g.k.deepa@intel.com>

2020-11-27 14:20 UTC, merged

2020-11-27 14:20 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Deepa, G K" <g.k.deepa@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2120