Add power profile in Celadon
projectceladon/device-androidia-mixins pull request #986
Opened 2020-11-27 14:15 UTC by kishanpadhiyar

Change-Id: I6900c6b328b44e37e28ce9cf84797807c0366648
Tracked-On: OAM-95309
Signed-off-by: rramakax <rohitx.kant@intel.com>
Signed-off-by: Kishan Mochi <kishan.mochi@intel.com>

2020-12-04 07:28 UTC, JeevakaPrabu requested changes
As the device doesn't have battery, I believe this are not real data. Please add this information in commit message. Also detail why this needs to be added

2020-12-07 08:35 UTC, kishanpadhiyar commented
@JeevakaPrabu, Data in this change is real.

2020-12-10 04:03 UTC, JeevakaPrabu approved these changes

2020-12-10 07:18 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2776

2020-12-10 07:39 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2777

2020-12-10 10:03 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-celr - r1 (caas), build-celr - r2 (r2_caas) - extra

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2778

2020-12-10 12:32 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-celr - r1 (caas), build-celr - r2 (r2_caas) - extra

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2780

2020-12-10 19:09 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2784

Done by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com>

2020-12-10 19:58 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1382

Done by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com>

2020-12-11 01:45 UTC, merged

2020-12-11 01:46 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2138