CIV: Fix sensor mediation hal reporting
projectceladon/device-androidia-mixins pull request #989
Opened 2020-12-01 09:07 UTC by kishanpadhiyar

Add android-removed-permissions.xml to
remove sensor features not supported
on CML NUC.
Add mixins option to support disable
static sensor list reported by hal.

Tracked-on: OAM-95331
Change-Id: I7eacbf8b2ed646c3a70b2fe68a89fd7bc3be0bf4
Signed-off-by: Swee Yee Fonn <swee.yee.fonn@intel.com>
Signed-off-by: Kishan Mochi <kishan.mochi@intel.com>

2020-12-04 07:51 UTC, JeevakaPrabu requested changes

2020-12-04 07:51 UTC, JeevakaPrabu commented on groups/device-specific/caas/android-removed-permissions.xml
> +</permissions>
Why removing when the copy itself can be prevented?

Feature files are copied from here device/intel/mixins/groups/sensors/mediation/product.mk, isn't it better to remove the PRODUCT_COPY_FILES in product.mk?

2020-12-08 04:55 UTC, kishanpadhiyar commented on groups/device-specific/caas/android-removed-permissions.xml
> +</permissions>
device/intel/mixins/groups/sensors/mediation/product.mk is suppose to be for all platforms, while these sensors are not supported for CML NUC. that's why _android-removed-permissions.xml_ is used.

2020-12-08 04:58 UTC, JeevakaPrabu commented on groups/device-specific/caas/android-removed-permissions.xml
> +</permissions>
caas is for all platforms.

2024-12-01 18:19 UTC, closed without merging