add device admin permissions
projectceladon/device-androidia-mixins pull request #992
Opened 2020-12-02 09:35 UTC by kishanpadhiyar

Tracked-on: OAM-95352
Signed-off-by: Basanagouda Koppad <Basanagoudax.n.Koppad@intel.com>
Signed-off-by: Kishan Mochi <kishan.mochi@intel.com>

2020-12-03 08:27 UTC, ceiba1985 approved these changes

2020-12-04 07:36 UTC, JeevakaPrabu requested changes

2020-12-04 07:36 UTC, JeevakaPrabu commented on groups/device-specific/caas/product.mk
> +product_copy_files += \
Use PRODUCT_COPY_FILES to be inline with rest of the file

2020-12-04 07:37 UTC, JeevakaPrabu requested changes
Please also add detailed commit message whats the issue and how is the patch fixing the issue

2020-12-10 04:05 UTC, JeevakaPrabu approved these changes

2020-12-10 07:19 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2776

2020-12-10 07:32 UTC, JeevakaPrabu approved these changes

2020-12-10 07:39 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2777

2020-12-10 08:04 UTC, JeevakaPrabu approved these changes

2020-12-10 10:03 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-celr - r1 (caas), build-celr - r2 (r2_caas) - extra

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2778

2020-12-10 12:32 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-celr - r1 (caas), build-celr - r2 (r2_caas) - extra

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2780

2020-12-10 19:09 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2784

Done by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com>

2020-12-10 19:58 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1382

Done by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com>

2020-12-11 01:46 UTC, merged

2020-12-11 01:47 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2138